create database airpassenger;
use airpassenger;

select*from aircraft_cleaned;
select*from airlines_cleaned;
select*from airports_cleaned;
select*from flights_cleaned;
select*from passengers_cleaned;
select*from routes_cleaned;
select*from staffs_cleaned;

-- 3. Passenger and Flight Details Using JOINs: Join the Passengers and Flights tables to display passenger details along with flight number, airline name, and destination airport.
select f.Flight_ID,p.Passenger_ID,p.Passenger_Name,f.Destination_Airport_ID,p.Nationality 
from passengers_cleaned p join flights_cleaned f
on p.Flight_ID=f.Flight_ID;

-- 4.Passenger Ticket and Travel Details :Use JOINs to display passenger name, ticket price, travel class, and flight status.
select p.Passenger_Name,p.Ticket_Price_USD,p.Travel_Class,f.Status 
from passengers_cleaned p join flights_cleaned f
on p.Flight_ID=f.Flight_ID;

-- 5. Highest Delay Flight Analysis:Find the flight with the highest delay and display its flight number, airline, route, and delay duration.
select max(Delay_Minutes) from airpassenger.flights_cleaned;

select f.Flight_ID,a.Airline_Name,r.Route_ID,f.Delay_Minutes
from flights_cleaned f
join airlines_cleaned a
on f.Airline_ID = a.Airline_ID
join routes_cleaned r
on f.Origin_Airport_ID = r.Origin_Airport_ID
and f.Destination_Airport_ID = r.Destination_Airport_ID
order by f.Delay_Minutes desc limit 1;

-- 6. Route Travel Time Analysis:Identify the routes with the highest and lowest average travel time.
select Origin_Airport_ID,Destination_Airport_ID,avg(Flight_Duration_Min) as Travel_Time 
from flights_cleaned
group by Origin_Airport_ID,Destination_Airport_ID
order by Travel_Time DESC LIMIT 1;

select Origin_Airport_ID,Destination_Airport_ID,avg(Flight_Duration_Min) as Travel_Time 
from flights_cleaned
group by Origin_Airport_ID,Destination_Airport_ID
order by Travel_Time ASC LIMIT 1;

-- 7. Airline Delay Performance:Calculate the average delay for each airline and identify the airline with the highest average delay.
select a.Airline_Name,a.country,avg(f.Delay_Minutes) as Avg_Delay
from airlines_cleaned a join flights_cleaned f
on a.Airline_ID=f.Airline_ID
group by a.Airline_Name
order by Avg_Delay Desc Limit 1;

-- 8. Load Factor by Route:Calculate the average load factor for each route to identify high- and low-performing routes.
select Route_ID,Avg_Load_Factor_Pct from routes_cleaned  order by Avg_Load_Factor_Pct DESC Limit 1;
select Route_ID,Avg_Load_Factor_Pct from routes_cleaned  order by Avg_Load_Factor_Pct ASC Limit 1;


-- 9. Monthly Load Factor Analysis:Analyze the average load factor for each route by month to identify changes in flight occupancy.
select Origin_Airport_Id,Destination_Airport_ID, MONTHNAME(Scheduled_Departure) AS Month,avg(Load_factor_Pct) as Avg_load_factor 
from flights_cleaned
group by Origin_Airport_Id,Destination_Airport_ID,MONTHNAME(Scheduled_Departure)
order by Origin_Airport_Id,Destination_Airport_ID,Month;

-- 10. Revenue by Route:Calculate the total revenue generated by each route and rank the routes from highest to lowest revenue.
select Route_ID,Total_Revenue_USD from routes_cleaned
order by Total_Revenue_USD desc;

-- 11. Underperforming Flight Analysis:Identify flights with a load factor below 60% and delay greater than 30 minutes.
select Load_Factor_Pct,Delay_Minutes from flights_cleaned 
where Load_Factor_Pct<60 and Delay_Minutes>30; 

-- 12. On-Time Performance Analysis:Calculate the number and percentage of delayed flights for each airline.
Select a.Airline_Name,count(CASE WHEN f.Delay_Minutes > 0 THEN 1 END) as  Delayed_Flights,
count(*) AS Total_Flights,
count(CASE WHEN f.Delay_Minutes > 0 THEN 1 END) * 100.0/ COUNT(*) AS Delay_Percentage FROM airlines_cleaned a
join flights_cleaned f on a.Airline_ID = f.Airline_ID
group by a.Airline_Name
order by Delay_Percentage desc;

-- 13. Delayed vs On-Time Passenger Satisfaction:Compare the average passenger satisfaction score between delayed and on-time flights.
select 
case 
when Delay_Minutes>0 Then "Flight Delayed"
Else "On Time"
End as Flight_Status,
avg(p.Satisfaction_Score) as Avg_Satisfaction_Score from flights_cleaned f
join passengers_cleaned p on f.Flight_ID=p.Flight_ID
group by 
case when Delay_Minutes>0 Then "Flight DeLayed"
Else "On Time"
End ;

-- 14. Route, Delay and Satisfaction Analysis:Analyze the average passenger satisfaction for each route based on flight status to understand how delays affect passenger experience.
select f.Origin_Airport_Id,f.Destination_Airport_ID,f.Status,avg(p.Satisfaction_Score) as Avg_Score from flights_cleaned f
join passengers_cleaned p
on f.Flight_ID=p.Flight_ID
group by Origin_Airport_Id,Destination_Airport_ID,f.Status;

-- 15. Top 5 Route Performance:Find the top 5 routes by total revenue and display their average load factor and average delay.
select Route_ID,Total_Revenue_USD,Avg_Load_Factor_Pct,Avg_Delay_Minutes from routes_cleaned 
order by Total_Revenue_USD desc Limit 5;

-- 16.Staff Distribution by Base Airport:Calculate the number of staff assigned to each base airport and identify the airports with the highest staff count.
select Base_Airport_ID,count(*) as Staff_Count from staffs_cleaned group by Base_Airport_ID
order by Staff_Count desc ;

-- 17.Experience vs Salary Analysis:Find the average salary for different experience levels and identify whether employees with more experience receive higher average salaries.
select Staff_Name,Experience_Years,avg(Salary_USD) as avg_salary from staffs_cleaned
group by Staff_Name, Experience_Years
order by Experience_Years desc;

-- 18.Role Salary Comparison:Calculate the average salary for each staff role and identify the highest-paying role.
select Role,avg(Salary_USD) as avg_salary from staffs_cleaned 
group by Role
order by avg_salary desc;

